trans_params:  
  epochs: 1
  lr: 0.0001
  batch_size: 128
  dim_val: 512
  input_seq_len: 30
  num_encoder_layers: 3
  num_heads: 16
  dropout_encoder: 0.2
  dropout_pos_enc: 0.1
  batch_first: True
files:
  train_data:
  test_data: 
path:
  project: '/Users/gclyne/thesis'
  data: '/Users/gclyne/thesis/data'
model:
  input: ['lai','tsl','mrsos','grassCropFrac','wetlandFrac','baresoilFrac','residualFrac','treeFrac','tas_DJF', 'tas_MAM', 'tas_JJA', 'tas_SON']
  output: ['cSoil','cCwd','cVeg','cLitter','cLeaf','cRoot','cStem','cOther']
