params:  
  epochs: 300
  lr: 0.0001
  batch_size: 1024

input: ['evspsblsoi', 'tsl','ps','pr','mrro','mrsos','grassCropFrac','wetlandFrac','baresoilFrac','residualFrac','treeFrac','tas_DJF', 'tas_MAM', 'tas_JJA', 'tas_SON']
# input: ['evspsblsoi','ps','tsl','mrro','mrsos','treeFrac','pr','tas_DJF', 'tas_MAM', 'tas_JJA', 'tas_SON']
#input: ['ps','treeFrac','tas_DJF', 'tas_MAM', 'tas_JJA', 'tas_SON','pr']
#input: ['treeFrac','tas_DJF','tas_JJA']
# output: ['cSoil','cCwd','cVeg','cLitter','cLeaf','cRoot','cStem','cOther','cSoilAbove1m']
output: ['cLeaf','cStem','cOther','cSoilAbove1m']
#only for cSoil
# input: ['evspsblsoi','mrro','mrsos','treeFrac']
# output: ['cSoilAbove1m']
id: ['year','lat','lon']

raw_cmip_variables: ['rMaint','rGrowth','nppWood','nppRoot','nppLeaf','nppOther','nppStem','cSoilAbove1m','cOther','cCwd','cVeg','cLitter','cLeaf','cRoot','evspsblsoi','lai','tsl','mrro','mrsos','grassFrac','shrubFrac','cropFrac','baresoilFrac','residualFrac','treeFrac','shrubFrac','cSoil','cStem','wetlandFrac','ps','pr','tas']
