params:  
  epochs: 100
  lr: 0.0001
  batch_size: 1024
  num_layers: 5
  hidden_units: 256
  seq_len: 30
  
input: ['tsl','ps','pr','mrro','mrsos','wetlandFrac','baresoilFrac','residualFrac','treeFrac','tas_DJF', 'tas_MAM', 'tas_JJA', 'tas_SON']
# input: ['evspsblsoi','ps','tsl','mrro','mrsos','treeFrac','pr','tas_DJF', 'tas_MAM', 'tas_JJA', 'tas_SON']
  #input: ['ps','treeFrac','tas_DJF', 'tas_MAM', 'tas_JJA', 'tas_SON','pr']
  #input: ['treeFrac','tas_DJF','tas_JJA']
  # output: ['cSoil','cCwd','cVeg','cLitter','cLeaf','cRoot','cStem','cOther','cSoilAbove1m']
output: ['cLeaf','cStem','cOther','cSoilAbove1m',çVeg','nppWood','nppRoot','nppLeaf']
  #only for cSoil
  # input: ['evspsblsoi','mrro','mrsos','treeFrac']
  # output: ['cSoilAbove1m']
id: ['year','lat','lon']
